### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by WhiteFox121** [mindsh4ke/witch-mobility-mod#8]
Minecraft 1.20.1 with Fabric Loader 0.15.11
fabric-api 0.92.2+1.20.1
geckolib 4.4.7
witchmobility-1.4.2-1.20.1
[crash.log](https://github.com/user-attachments/files/16967752/crash.log)

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'witchmobility'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.11.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_756
	at net.mindshake.witchmobility.registry.ModItems.<clinit>(ModItems.java:17) ~[witchmobility-1.4.2-1.20.1.jar:?]
	at net.mindshake.witchmobility.Main.onInitialize(Main.java:23) ~[witchmobility-1.4.2-1.20.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_756
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.mindshake.witchmobility.registry.ModItems.<clinit>(ModItems.java:17) ~[witchmobility-1.4.2-1.20.1.jar:?]
	at net.mindshake.witchmobility.Main.onInitialize(Main.java:23) ~[witchmobility-1.4.2-1.20.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 6 more

**Comment by Otabee** [comment]
i also have this issue 1.20.1 fabric loader 1.16.5
According to curseforge comments, the issue was seen for the 1.19.2 version and fixed. I'm hoping the 1.20.1 version just needs the same fix.

**Comment by mindsh4ke** [comment]
Issue fixed in the new 1.4.3 version. Now available in curseforge. Thank you for reporting!! :)
